### ISSUE TITLE
Global versionDropDownItem

### ISSUE THREAD

**Issue by karl-cardenas-coding** [spectrocloud/librarium#1561]
@nagesh161007 I might have found a nice lil challenge for you. Take a peek at the [README's versioning](https://github.com/spectrocloud/librarium#versioning) first

The current docs site is a multi-site that uses two plugins to render the default docs and the API. 
The default docs version drop-down only applies to the default plugin. The API plugin `api` is not included when a user selects a version. 

To address this, we need to create global version selector. There is an example [here](https://stackoverflow.com/questions/75229184/docusaurus-how-can-i-have-multiple-versions-of-different-docs-in-the-docs-direc) of how someone achieved this. 

To generate the version content for the `api` plugin, use the command:
```shell
npx docusaurus docs:version:id 4.0.x
```

This will generate the following content:
- `api_versions.json` - versions file for the API.
- `api_versioned_docs/` - folder containing all versioned docs.
- `api_versionioned_sidebars/` - folder containing the API sidebar.
This would also require the `docusaurs_config.js` file to get updated:
```js
  plugins: ["docusaurus-plugin-sass", ["@docusaurus/plugin-content-docs", {
    id: "api",
    path: "docs/api-content/api-docs",
    routeBasePath: "api",
    docItemComponent: "@theme/ApiItem",
    sidebarPath: require.resolve("./apisidebar.js"),
    versions: {
      current: {
        label: "latest"
      },
      "4.0.x": {
        banner: "none",
        label: "v4.0.x"
      },
      "3.4.x": {
        banner: "none",
        label: "v3.4.x and prior"
      }
    }
  }],
```

**Comment by karl-cardenas-coding** [comment]
Related https://github.com/facebook/docusaurus/issues/4389

**Comment by nagesh161007** [comment]
Sure @karl-cardenas-coding. Will check this and let you know

**Comment by nagesh161007** [comment]
Hi @karl-cardenas-coding , I have made some changes for this yesterday. Will test this and raise PR soon

**Comment by karl-cardenas-coding** [comment]
Awesome, I'm exited to test it out 😄
