### ISSUE TITLE
Fix Mendable Floating Button Logo

### ISSUE THREAD

**Issue by karl-cardenas-coding** [spectrocloud/librarium#1568]
The Mendable floating button does not display the specified assets.

**Comment by nagesh161007** [comment]
Hi @karl-cardenas-coding, I've created a solution for this issue, but I can't push my changes since I don't have write permissions for this repository. I'm no longer part of the Spectrocloud organization on GitHub. Should I fork this repository and create pull request. Meanwhile I am posting changes for Mendable AI widget here. Moved `icon` and `botIcon` outside floatingButton in config and removed imports and directly used image urls

```

import { useEffect } from "react";
import useDocusaurusContext from "@docusaurus/useDocusaurusContext";
import useBaseUrl from "@docusaurus/useBaseUrl";

export const MENDABLE_SCRIPT_URL =
  "https://unpkg.com/@mendable/search@0.0.155/dist/umd/mendable-bundle.min.js";

export default function MendableAIWidget() {
  const {
    siteConfig: { customFields },
  } = useDocusaurusContext();

  const logoUrl = useBaseUrl("/spectrocloud-logo.png");
  const botUrl = useBaseUrl("/spectrocloud-logo-black.svg");

  useEffect(() => {
    const script = document.createElement("script");
    script.src = MENDABLE_SCRIPT_URL;
    script.defer = true;

    setTimeout(() => {
      document.body.appendChild(script);
    }, 500);

    script.onload = () => {
      if (window.Mendable) {
        window.Mendable.initialize({
          anon_key: customFields?.mendableKey,
          type: "floatingButton",
          dialogPlaceholder: "What is Palette?",
          cmdShortcutKey: "l",
          icon: logoUrl,
          botIcon: botUrl,
          floatingButtonStyle: {
            color: "#FFFFFF",
            backgroundColor: "#3E4FB5",
          },
          isPinnable: true,
          style: { accentColor: "#3E4FB5" },
        });
      }
    };

    return () => {
      document.body.removeChild(script);
    };
  }, []);

  return null;
}


```

**Comment by karl-cardenas-coding** [comment]
Hi @nagesh161007 , ahhh that's right. Hm, yeah let's try the fork route. I can approve the CI workflow for the fork.

**Comment by nagesh161007** [comment]
Hi @karl-cardenas-coding , I am not sure why Github CI/CD actions were failing for my PR. I think that environment variables are not getting loaded properly for PR from fork.

**Comment by karl-cardenas-coding** [comment]
@nagesh161007 That's exactly why. GitHub automatically removes CI variables in forked CI actions. A different workflow is needed to allow fork runs to start
