### ISSUE TITLE
Deprecated Packs Table  Caching Issue

### ISSUE THREAD

**Issue by karl-cardenas-coding** [spectrocloud/librarium#1737]
The deprecated packs table is caching the packs JSON data during local builds and in Netlify.  It's using the JSON data from 
 `dateCreated": "2023-08-17T12:09:22.663428168Z`

This needs to be fixed so version branches display the correct data. Example:
https://version-3-4.legacy.docs.spectrocloud.com/integrations/deprecated-packs

**Comment by karl-cardenas-coding** [comment]
@nagesh161007 Any ideas as to why this is cached locally and in Netlify?

**Comment by nagesh161007** [comment]
Hi @karl-cardenas-coding , its no cached. The packs github action updates the json directly in S3 bucket.  netlify and local doesn’t have the updated packs as we are not committing the json file in our repository

**Comment by karl-cardenas-coding** [comment]
@nagesh161007 that's the behavior we see in prod. But try for yourself to bring up the local server. It's using an old version of the file 🤔

**Comment by karl-cardenas-coding** [comment]
@nagesh161007 we figured it out. Or, more accurately, @lennessyy figured it out. Local builds and Netlify are using the `static` folder and in there we have an old copy from August 😓 

Hope school is going well @nagesh161007.

**Comment by nagesh161007** [comment]
Hi @karl-cardenas-coding, Local and Netlify uses packs_report.json from static folder. But in s3 bucket it gets updated every 6 hours so we have new file in prod. 

`https://github.com/spectrocloud/librarium/blob/master/static/packs-data/packs_report.json`

School is going good Karl. Hope everything is going well with our docs.
