### ISSUE TITLE
Video Not Rendering in Docusaurus V3

### ISSUE THREAD

**Issue by lennessyy** [spectrocloud/librarium#1997]
Hi @nagesh161007 ,

Nice to meet you! My name is Lenny and I'm a Sr. Technical Writer on Karl's team. Thanks for your previous help with the JS issue.

We have run into another issue with video not rendering correctly on Docusaurus 3.

See this page: https://deploy-preview-1995--docs-spectrocloud.netlify.app/vertex/install-palette-vertex/install-on-vmware/install

The video component does not have the properties we defined in the Video.tsx file and it does not play. If we add in the html properties manually, it works and plays fine. Do you know what's causing this?

**Comment by karl-cardenas-coding** [comment]
@ nagesh161007 I think this might be related to the React 18 upgrade under the covers.  If you're curious, here is their [blog](https://docusaurus.io/blog/preparing-your-site-for-docusaurus-v3#admonition-warning) on migrating from v2 to v3.

**Comment by lennessyy** [comment]
I think the `<video>` tag in the document might be using the default HTML element tag instead of the custom one that we defined. I just added some properties to the tag itself and that seems to make it work:

```
<video title="palette-cli-install" controls loop playsinline src="/videos/palette-install.mp4"></video>
```

**Comment by nagesh161007** [comment]
Hi @lennessyy and @karl-cardenas-coding. Checking on this. I will update here once I find the solution.

**Comment by nagesh161007** [comment]
Hi @lennessyy and @karl-cardenas-coding . From V3 its mentioned custom Mdx components with lower case will be rendered as native html elements. Either we need to convert the component to Upper case or go with native video tag.

https://docusaurus.io/docs/markdown-features/react#mdx-component-scope

**Comment by nagesh161007** [comment]
```
const customMdxComponents = {
  img: (props) => {
    const widthMatch = props?.title?.match(widthRegex);
    const customWidth = widthMatch && widthMatch.length > 1 ? widthMatch[1] : null;
    const isEagerLoading = eagerLoadRegex.test(props.alt);
    const loadingTechnique = isEagerLoading ? "eager" : "lazy";
    const fetchpriority = isEagerLoading ? "high" : "auto";

    return (
      <img
        className="markdown-image"
        {...props}
        style={customWidth ? { width: customWidth } : {}}
        loading={loadingTechnique}
        // eslint-disable-next-line react/no-unknown-property
        fetchpriority={fetchpriority}
      />
    );
  },
  Video: Video,
};

```

We can change the `video` to `Video`.


Example 

Before

`<video title="palette-cli-install" src="/videos/vertex-install.mp4"></video>`

After

`<Video title="palette-cli-install" src="/videos/vertex-install.mp4"></Video>`

**Comment by karl-cardenas-coding** [comment]
That explains the behavior we are seeing perfectly. Thank you so much @nagesh161007 we'll give it a try here shortly 💪🏻

**Comment by lennessyy** [comment]
Yep that's it. Just tried and it works perfectly. Thanks @nagesh161007 !

**Comment by nagesh161007** [comment]
Thanks @lennessyy and @karl-cardenas-coding
