### ISSUE TITLE
Font has changed in the docs

### ISSUE THREAD

**Issue by abhikb2005** [spectrocloud/librarium#250]
This issue has been created from [this](https://spectrocloud.slack.com/archives/G01DJU1JU65/p1605878462002500) Slack chat.

**Comment by codrin-iftimie** [comment]
![image (5)](https://user-images.githubusercontent.com/2052603/115236964-a8ee0d80-a124-11eb-80d7-4625e1a4502d.png)

**Comment by codrin-iftimie** [comment]
I this was fixed here: https://github.com/spectrocloud/librarium/pull/256

**Comment by IonitaCatalina** [comment]
Issue was fixed 
<img width="1619" alt="Screen Shot 2021-04-19 at 15 46 44" src="https://user-images.githubusercontent.com/10097274/115238839-d20f9d80-a126-11eb-905b-12c89b44e02b.png">
