### ISSUE TITLE
Code blocks in InfoBox and WarningBox

### ISSUE THREAD

**Issue by abhikb2005** [spectrocloud/librarium#251]
The MD syntax for a phrase in code is not translating correctly into HTML. An example screenshot is available in [this](https://spectrocloud.slack.com/archives/G01DJU1JU65/p1605878890005100) Slack chat.

The MD syntax that was tried was taken from [here](https://www.markdownguide.org/basic-syntax/#code).

**Comment by codrin-iftimie** [comment]
```
<InfoBox>
Note that Ubuntu is <code>systemd</code> based.
</InfoBox>
```
produces
![image (4)](https://user-images.githubusercontent.com/2052603/115236820-80feaa00-a124-11eb-9020-1c5b969c659b.png)

**Comment by IonitaCatalina** [comment]
issue is fixed
![Uploading Screen Shot 2021-04-19 at 16.11.17.png…]()
